# Generated by Django 2.1.8 on 2019-06-10 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('check_price', models.FloatField(blank=True, null=True)),
                ('complete_price', models.FloatField(blank=True, null=True)),
                ('max_price', models.FloatField(blank=True, null=True)),
                ('today_result', models.FloatField(blank=True, null=True)),
                ('result_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
